language: node_js
node_js: lts/*
services:
  - xvfb
before_install:
  - sudo apt-get install libgconf-2-4
  - npm install -g yarn
script: yarn test
sudo: false
git:
  depth: 3
cache:
  directories:
  - node_modules
  - ".cache"
